# Generated by Django 5.2.6 on 2025-09-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('fast-food', 'Fast Food'), ('cafe', 'Cafe'), ('fine-dining', 'Fine Dining'), ('light-meals', 'Light Meals'), ('desserts', 'Desserts')], default='other', max_length=50),
        ),
    ]
