# Generated by Django 5.2.7 on 2025-11-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_shop_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dnv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='upv',
            field=models.IntegerField(default=0),
        ),
    ]
