# Generated by Django 5.2.7 on 2025-11-11 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_dnv_review_upv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
